# Generated by Django 3.1.7 on 2021-03-07 17:12
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Group', 'Group')], db_index=True, max_length=15)),
                ('body', models.TextField(null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('notification_language', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-date_sent',),
            },
        ),
    ]
